# Generated by Django 5.2.9 on 2026-01-02 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='商品标题')),
                ('category_id', models.IntegerField(verbose_name='所属二级分类ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品价格')),
                ('quality', models.SmallIntegerField(choices=[(1, '新'), (2, '较新'), (3, '一般')], verbose_name='成色')),
                ('status', models.SmallIntegerField(choices=[(1, '在售'), (2, '下架'), (3, '已卖出')], default=1, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'goods',
            },
        ),
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='分类名称')),
                ('parent_id', models.IntegerField(default=0, verbose_name='父分类ID')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
                'db_table': 'goods_category',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='手机号')),
                ('password', models.CharField(max_length=128, verbose_name='加密密码')),
                ('nickname', models.CharField(max_length=32, verbose_name='用户昵称')),
                ('status', models.SmallIntegerField(choices=[(1, '正常'), (0, '禁用')], default=1, verbose_name='状态')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='订单金额')),
                ('status', models.SmallIntegerField(choices=[(1, '待支付'), (2, '已支付'), (3, '已完成'), (4, '已取消')], default=1, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='交易时间')),
                ('goods', models.ForeignKey(db_column='goods_id', on_delete=django.db.models.deletion.PROTECT, to='trade.goods', verbose_name='商品')),
                ('buyer', models.ForeignKey(db_column='buyer_id', on_delete=django.db.models.deletion.PROTECT, related_name='buyer_orders', to='trade.user', verbose_name='买家')),
                ('seller', models.ForeignKey(db_column='seller_id', on_delete=django.db.models.deletion.PROTECT, related_name='seller_orders', to='trade.user', verbose_name='卖家')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'order',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='publisher',
            field=models.ForeignKey(db_column='publisher_id', on_delete=django.db.models.deletion.PROTECT, to='trade.user', verbose_name='发布者'),
        ),
    ]
