# Generated by Django 5.2.9 on 2026-01-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_user_role_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='image',
            field=models.URLField(db_column='image', default='', verbose_name='商品图片'),
            preserve_default=False,
        ),
    ]
