# Generated by Django 5.2.9 on 2026-01-27 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_goods_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='details',
            field=models.CharField(default='卖家啥也没写哦。。。。。。', max_length=800, verbose_name='商品详情'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='image',
            field=models.ImageField(db_column='image', upload_to='product_images/', verbose_name='商品图片'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='quality',
            field=models.SmallIntegerField(verbose_name='成色'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '未支付'), (1, '已支付')], default=0, verbose_name='状态'),
        ),
    ]
