# Generated by Django 5.2.9 on 2026-01-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_goods_details_alter_goods_image_alter_goods_quality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='details',
            field=models.CharField(default='卖家啥也没写。。。。。。', max_length=800, verbose_name='商品详情'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '在售'), (2, '已卖出')], default=1, verbose_name='状态'),
        ),
    ]
