# Generated by Django 5.2.9 on 2026-01-30 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_alter_goods_details_alter_goods_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.SmallIntegerField(choices=[(1, '普通用户'), (2, '管理员'), (3, '超级管理员')], default=1, verbose_name='用户角色'),
        ),
    ]
