# Generated by Django 5.2.9 on 2026-02-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0007_alter_goods_status_userwish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '在售'), (2, '已卖出'), (3, '已下架'), (4, '强制下架')], default=1, verbose_name='状态'),
        ),
    ]
