"""
Django settings for AmionsProject project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

import rest_framework
from rest_framework.views import exception_handler
from channels_redis.core import RedisChannelLayer

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6wsdn_c$=colug@ev@f=guk@#aee=-9r1%^$h&4(ym+1w&3xuq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'trade',
    'login',
    'rest_framework',
    'rest_framework_simplejwt',
    'profiles',
    'sign',
    'details',
    'settlement',
    'admin_manage',
    'chat',
    'aichat'
]


#允许携带cookie
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = True
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

# 允许所有请求头
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]
CORS_PREFLIGHT_MAX_AGE = 86400

ROOT_URLCONF = 'AmionsProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'AmionsProject.wsgi.application'
ASGI_APPLICATION = 'AmionsProject.asgi:application'  #WebSocket必备

#聊天室,用redis做消息通道
CHANNEL_LAYERS={
    'default':{
        "BACKEND":"channels.layers.InMemoryChannelLayer",
        "CONFIG":{
            "hosts":{('192.168.31.238',6379)}
        }
    }
}

#redis缓存配置
CACHES={
    "default":{
        "BACKEND":"django_redis.cache.RedisCache",
        "LOCATION":"redis://127.0.0.1:6379/2",  # 使用 Redis db2 (数据库索引为2)
        "OPTIONS":{
            "CLIENT_CLASS":"django_redis.client.DefaultClient",
            # "PASSWORD":"123123"  # 取消注释此行，如果您的 Redis 服务器设置了密码
        },
        "KEY_PREFIX": "AmionsProject_cache"
    }
}

# Channels配置
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

#数据库配置基础信息
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'amionsnuaa',
        'USER': 'root',
        'PASSWORD': '123123',
        'HOST': 'localhost',
        'PORT': '3305',
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

#时区
USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

#静态文件存放位置
STATIC_URL = 'static/'
STATICFILES_DIRS=[
    BASE_DIR / 'static',
]


MEDIA_URL = '/media/'  # 访问媒体文件的 URL 前缀
MEDIA_ROOT = BASE_DIR / 'media'  # 媒体文件存放的实际路径


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# JWT Token配置
from datetime import timedelta
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'EXCEPTION_HANDLER': rest_framework.views.exception_handler,
}
# 添加自定义User模型配置
AUTH_USER_MODEL = 'trade.User'

# 完善SimpleJWT配置
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=3),
    'USER_ID_FIELD': 'id',  # 指定使用哪个字段作为用户ID
    'ALGORITHM': 'HS256',
    'CHECK_ACTIVE': False,
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'AmionsProject': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

#是否为内网穿透环境
USE_PEANUT_SHELL = True

# 支付宝配置
ALIPAY_APPID = '9021000159649709'
ALIPAY_DEBUG = True
ALIPAY_URL = 'https://openapi-sandbox.dl.alipaydev.com/gateway.do'

#根据环境动态判断
LOCAL_BASE_URL = 'http://192.168.31.238'
PEANUT_SHELL_BASE_URL = 'http://69mdjw853446.vicp.fun'
LOCAL_PORT = 8000
PEANUT_SHELL_PORT = 37276

# 根据开关自动赋值
if USE_PEANUT_SHELL:
    BASE_URL = PEANUT_SHELL_BASE_URL
    PORT = PEANUT_SHELL_PORT
    FRONTEND_BASE_URL = 'http://69mdjw853446.vicp.fun'
else:
    BASE_URL = LOCAL_BASE_URL
    PORT = LOCAL_PORT
    FRONTEND_BASE_URL = 'http://192.168.31.238:5173'

ALIPAY_RETURN_URL = f'{BASE_URL}:{PORT}/api/settlement/settlementSuccess/'
FRONTEND_BASE_URL = FRONTEND_BASE_URL


