# Generated by Django 5.2.9 on 2026-02-07 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("trade", "0008_alter_goods_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room_name",
                    models.CharField(
                        max_length=50, verbose_name="房间名，格式：room_小ID_大ID"
                    ),
                ),
                ("content", models.TextField(verbose_name="消息内容")),
                (
                    "message_type",
                    models.CharField(
                        choices=[("text", "文本"), ("image", "图片"), ("file", "文件")],
                        default="text",
                        max_length=10,
                        verbose_name="消息类型",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="是否已读"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to="trade.user",
                        verbose_name="接收者",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to="trade.user",
                        verbose_name="发送者",
                    ),
                ),
            ],
            options={
                "verbose_name": "聊天消息",
                "verbose_name_plural": "聊天消息",
                "db_table": "chat_messages",
                "indexes": [
                    models.Index(
                        fields=["room_name", "created_at"], name="idx_room_time"
                    ),
                    models.Index(
                        fields=["receiver", "is_read", "created_at"],
                        name="idx_receiver_unread",
                    ),
                    models.Index(
                        fields=["sender", "created_at"], name="idx_sender_time"
                    ),
                ],
            },
        ),
    ]
